name: Block DO NOT SUBMIT
on: [pull_request]
jobs:
  block_do_not_submit:
    runs-on: ubuntu-latest
    env:
      BLOCKED_PATTERN: "DO NOT SUBMIT"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Block DO NOT SUBMIT
        run: |
          if grep -E -H "$BLOCKED_PATTERN" $(git diff --name-only origin/${{ github.event.pull_request.base.ref }}) /dev/null; then
            echo "$BLOCKED_PATTERN found in the PR. Please remove it before merging."
            exit 1
          fi